#!/usr/bin/env node
/**
 * Vendor the PalletBallet client engine into this repo.
 *
 * The engine's source of truth is `physics-sim/web/src` — that's where the
 * parity suite lives (byte-identical MJCF, verdict agreement against the fp64
 * CPU engine, seed-for-seed generator parity). None of that can run here, so
 * this repo carries a *copy*, not a fork: never edit
 * `src/lib/palletballet-engine/` by hand, change it upstream and re-sync.
 *
 * Vendoring rather than depending on a package because the engine lives in a
 * subdirectory of another repo, which npm can't install from a git URL, and
 * publishing to npm is a bigger decision than this integration needs.
 *
 *   node scripts/sync-engine.mjs [--source ../physics-sim/web/src] [--check]
 *
 * `--check` verifies the vendored copy is current without writing (for CI).
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..');
const DEST = path.join(REPO, 'src/lib/palletballet-engine');

const args = process.argv.slice(2);
const argOf = (flag, dflt) => (args.includes(flag) ? args[args.indexOf(flag) + 1] : dflt);
const CHECK = args.includes('--check');
// --verify needs no upstream checkout: it re-hashes the vendored directory and
// compares against the manifest, catching hand-edits to a directory whose whole
// contract is "generated, don't touch". That's the check CI can actually run.
const VERIFY = args.includes('--verify');
const SOURCE = path.resolve(REPO, argOf('--source', '../physics-sim/web/src'));

/** Hash every file's path + contents, so drift is detectable without a diff. */
function fingerprint(dir, skip = new Set()) {
  const h = createHash('sha256');
  const walk = (d, rel = '') => {
    for (const name of readdirSync(d).sort()) {
      const full = path.join(d, name);
      const r = rel ? `${rel}/${name}` : name;
      if (skip.has(r)) continue;
      if (statSync(full).isDirectory()) walk(full, r);
      else { h.update(r); h.update(readFileSync(full)); }
    }
  };
  walk(dir);
  return h.digest('hex').slice(0, 16);
}

/** Fingerprint of the vendored copy itself, ignoring the manifest. */
const vendoredPrint = () => fingerprint(DEST, new Set(['VENDORED.json']));

function sourceCommit() {
  try {
    return execFileSync('git', ['-C', path.dirname(SOURCE), 'rev-parse', '--short', 'HEAD'],
      { encoding: 'utf8' }).trim();
  } catch {
    return 'unknown';
  }
}

if (VERIFY) {
  if (!existsSync(manifestPathEarly())) {
    console.error('engine not vendored — run: node scripts/sync-engine.mjs');
    process.exit(1);
  }
  const m = JSON.parse(readFileSync(manifestPathEarly(), 'utf8'));
  const actual = vendoredPrint();
  if (m.vendored_fingerprint !== actual) {
    console.error(`vendored engine was edited in place (${actual} != ${m.vendored_fingerprint})`);
    console.error('src/lib/palletballet-engine is generated — change it upstream and re-sync.');
    process.exit(1);
  }
  console.log(`vendored engine intact (${actual}, from ${m.source_commit})`);
  process.exit(0);
}

function manifestPathEarly() {
  return path.join(DEST, 'VENDORED.json');
}

if (!existsSync(SOURCE)) {
  console.error(`engine source not found: ${SOURCE}`);
  console.error('Pass --source <path-to-physics-sim/web/src> if the repo lives elsewhere.');
  process.exit(1);
}

const srcPrint = fingerprint(SOURCE);
const manifestPath = path.join(DEST, 'VENDORED.json');
const current = existsSync(manifestPath)
  ? JSON.parse(readFileSync(manifestPath, 'utf8'))
  : null;

if (CHECK) {
  if (!current) { console.error('engine not vendored yet — run: node scripts/sync-engine.mjs'); process.exit(1); }
  if (current.fingerprint !== srcPrint) {
    console.error(`vendored engine is STALE (${current.fingerprint} != ${srcPrint})`);
    console.error('run: node scripts/sync-engine.mjs');
    process.exit(1);
  }
  console.log(`vendored engine is current (${srcPrint})`);
  process.exit(0);
}

rmSync(DEST, { recursive: true, force: true });
mkdirSync(DEST, { recursive: true });
cpSync(SOURCE, DEST, { recursive: true });

// The Node-only spike script has no place in a browser bundle.
rmSync(path.join(DEST, 'spike.mjs'), { force: true });

writeFileSync(manifestPath, `${JSON.stringify({
  source: path.relative(REPO, SOURCE),
  source_commit: sourceCommit(),
  fingerprint: srcPrint,
  vendored_fingerprint: vendoredPrint(),
  note: 'Generated by scripts/sync-engine.mjs — do not edit this directory by hand.',
}, null, 2)}\n`);

const files = readdirSync(DEST).length;
console.log(`vendored engine → src/lib/palletballet-engine (${files} entries, fingerprint ${srcPrint})`);
